In [9]:
import cv2
import os
import numpy

In [5]:
os.listdir()

['.ipynb_checkpoints',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'TratamientoDeImagenes.ipynb']

In [6]:
imagenGris = cv2.imread('smallgray.png', 0)
print(imagenGris)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [7]:
cv2.imwrite('nuevaimagen.png', imagenGris)

True

In [10]:
nuevo = numpy.vstack((imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris, imagenGris))
print(nuevo)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [12]:
cv2.imwrite('nuevaimagenGrande.png', nuevo)

True